spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/secDB?currentSchema=sec
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
